### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by ArthurConan** [cihangxie/NIPS2017_adv_challenge_defense#1]
Hi! Sorry for disturbing, but I wonder:
what for you use this parameter "itr"? why we need resize image many times?
and why we need "aux_pred" ?
many thanks in advance!!!

**Comment by cihangxie** [comment]
Why resize image many times: The purpose is to obtained an ensemble of random patterns for classification, which usually have higher accuracy. In practice, you can set itr = 1 for fast speed. You can also refer the effectiveness of "itr" at last page in our paper https://arxiv.org/pdf/1711.01991.pdf. 

Why use "aux_pred": Use aux_pred let model get higher accuracy on clean images.
