### ISSUE TITLE
Padding_zero

### ISSUE THREAD

**Issue by ArthurConan** [cihangxie/NIPS2017_adv_challenge_defense#2]
Hi again, thanks for the last answer, it was informative and fast!
I have ultimate question - I hope, you can help me to understand one more thing:
why it is useful to add Zero pixels (Zero padding)? Especially for black-box attack
(I read your article, but still don't get it. hope. Sorry me - silly girl - I just start to learn adv samples)

**Comment by cihangxie** [comment]
Hi, 
As we pointed in the paper, traditional adversarial examples tend to fit into a fixed pattern and cannot transfer well. Random padding and random resizing both give us a way to create different patterns, thus can defend against adversarial example well under certain situations.
