### ISSUE TITLE
How to get data?

### ISSUE THREAD

**Issue by nooooonee** [cihangxie/NIPS2017_adv_challenge_defense#3]
Hi,  I have some questions about input data.  Could I know how did you do the pre-processing for getting input data whose shape is 299*299?  And in fact, the data in Imagenet is not bound to 299*299.  I would appreciate your help.

**Comment by cihangxie** [comment]
yes, all images are pre-processed to 299x299. You can get these data from https://github.com/tensorflow/cleverhans/tree/master/examples/nips17_adversarial_competition/dataset

Or you can refer https://arxiv.org/abs/1804.00097 for more details

**Comment by pengdan1129** [comment]
I got it. Thanks a lot!

**Comment by yearep7** [comment]
Hi，these data from https://github.com/tensorflow/cleverhans/tree/master/examples/nips17_adversarial_competition/dataset  is not work，can you send a new website，please
