### ISSUE TITLE
A strange line in defense.py

### ISSUE THREAD

**Issue by KunlinLiu** [cihangxie/NIPS2017_adv_challenge_defense#4]
code:   
 output_long = tf.to_int32(tf.ceil(
        1. * tf.to_float(output_short) * tf.to_float(input_long) / tf.to_float(input_short)))

Was the '1.*' wrong ? 
 Why is there three ')'? 
Maybe I miss some important key points.
Could you plz give me some help ? 
Thank you !

**Comment by bairdzhang** [comment]
We are trying to compute the long side of the output by ceil(out_short*in_long/in_short).

I am not sure the 1.* is necessary but I think keeping it won't make it wrong.

There are three ')'s because there are two '('s in the previous line, and there is another '(' for the last 'tf.to_float'.
